// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK3GlANl5eoI71HTHU8mUojTm133-IXQI',
    appId: '1:6936929859:web:922975ed358e00327416f6',
    messagingSenderId: '6936929859',
    projectId: 'mediago-1bd0a',
    authDomain: 'mediago-1bd0a.firebaseapp.com',
    storageBucket: 'mediago-1bd0a.firebasestorage.app',
    measurementId: 'G-F6ZE275NMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiN4a-y1z7b-JevplwMRrQAQReHjIm1Y8',
    appId: '1:6936929859:android:92f128d7bcc394587416f6',
    messagingSenderId: '6936929859',
    projectId: 'mediago-1bd0a',
    storageBucket: 'mediago-1bd0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0dO80abpZ6JNVtm7RRU3kXW0eQtbscfo',
    appId: '1:6936929859:ios:5a426ed101996ecf7416f6',
    messagingSenderId: '6936929859',
    projectId: 'mediago-1bd0a',
    storageBucket: 'mediago-1bd0a.firebasestorage.app',
    iosBundleId: 'com.example.medigo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0dO80abpZ6JNVtm7RRU3kXW0eQtbscfo',
    appId: '1:6936929859:ios:5a426ed101996ecf7416f6',
    messagingSenderId: '6936929859',
    projectId: 'mediago-1bd0a',
    storageBucket: 'mediago-1bd0a.firebasestorage.app',
    iosBundleId: 'com.example.medigo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK3GlANl5eoI71HTHU8mUojTm133-IXQI',
    appId: '1:6936929859:web:2d4e34b0e4d534b07416f6',
    messagingSenderId: '6936929859',
    projectId: 'mediago-1bd0a',
    authDomain: 'mediago-1bd0a.firebaseapp.com',
    storageBucket: 'mediago-1bd0a.firebasestorage.app',
    measurementId: 'G-EY7G803FB7',
  );
}
